#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import struct
import wave
from pathlib import Path

REQUIRED_RATE = 48_000
MAX_UNIT_SECONDS = 12.0


def c_ident(key: str, index: int) -> str:
    return f"sr_voice_pcm_{index:04d}"


def load_wav(path: Path) -> list[int]:
    with wave.open(str(path), "rb") as wav:
        if wav.getnchannels() != 1:
            raise SystemExit(f"{path}: expected mono WAV")
        if wav.getsampwidth() != 2:
            raise SystemExit(f"{path}: expected signed PCM16 WAV")
        if wav.getframerate() != REQUIRED_RATE:
            raise SystemExit(f"{path}: expected {REQUIRED_RATE} Hz")
        frames = wav.getnframes()
        if frames <= 0:
            raise SystemExit(f"{path}: empty WAV")
        if frames > int(REQUIRED_RATE * MAX_UNIT_SECONDS):
            raise SystemExit(f"{path}: unit exceeds {MAX_UNIT_SECONDS:.0f}s")
        raw = wav.readframes(frames)
    samples = list(struct.unpack("<" + "h" * frames, raw))
    peak = max(abs(v) for v in samples)
    if peak >= 32767:
        raise SystemExit(f"{path}: clipped PCM")
    dc = abs(sum(samples) / len(samples))
    if dc > 700:
        raise SystemExit(f"{path}: excessive DC offset ({dc:.1f})")
    return samples


def emit_i16(name: str, values: list[int]) -> str:
    lines: list[str] = []
    for i in range(0, len(values), 16):
        lines.append("    " + ", ".join(str(v) for v in values[i:i+16]) + ",")
    return f"static const sr_pcm16 {name}[] = {{\n" + "\n".join(lines) + "\n};\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", type=Path)
    parser.add_argument("output_c", type=Path)
    parser.add_argument("--header", default="sr_voice_stream.h")
    args = parser.parse_args()

    data = json.loads(args.manifest.read_text(encoding="utf-8"))
    units = data.get("units")
    if not isinstance(units, list) or not units:
        raise SystemExit("manifest must contain a non-empty units array")

    seen: set[str] = set()
    arrays: list[str] = []
    rows: list[str] = []
    base = args.manifest.parent

    for index, item in enumerate(units):
        if not isinstance(item, dict):
            raise SystemExit(f"unit {index}: expected object")
        key = item.get("key")
        wav_name = item.get("wav")
        if not isinstance(key, str) or not key or len(key.encode("utf-8")) > 96:
            raise SystemExit(f"unit {index}: invalid key")
        if key in seen:
            raise SystemExit(f"duplicate key: {key}")
        if not isinstance(wav_name, str) or not wav_name:
            raise SystemExit(f"unit {index}: invalid wav")
        seen.add(key)

        samples = load_wav((base / wav_name).resolve())
        name = c_ident(key, index)
        arrays.append(emit_i16(name, samples))
        escaped = key.replace("\\", "\\\\").replace('"', '\\"')
        rows.append(f'    {{"{escaped}", {name}, {len(samples)}u}},')

    output = [
        "/* Generated by pack_voice_bank.py; do not edit. */",
        f'#include "{args.header}"',
        "",
        *arrays,
        "const sr_voice_unit sr_quality_voice_units[] = {",
        *rows,
        "};",
        f"const sr_u32 sr_quality_voice_unit_count = {len(rows)}u;",
        "const sr_voice_bank sr_quality_voice_bank = {",
        "    sr_quality_voice_units,",
        "    sr_quality_voice_unit_count,",
        f"    {REQUIRED_RATE}u",
        "};",
        "",
    ]
    args.output_c.parent.mkdir(parents=True, exist_ok=True)
    args.output_c.write_text("\n".join(output), encoding="utf-8")
    print("UEFI_QUALITY_VOICE_BANK=PASS")
    print(f"units={len(rows)}")
    print(f"sample_rate={REQUIRED_RATE}")


if __name__ == "__main__":
    main()
