#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import struct
import sys
from pathlib import Path

TEXT_RVA = 0x1000
DATA_RVA = 0x4000
SAMPLE_RATE = 16000
UNIT_MS = 95
TAU = 6.283185307179586

# First-party, deterministic speech units. These are not recordings and are not
# generated by an external TTS engine. The EFI runtime concatenates these units
# according to PHRASES below.
UNIT_SPECS = {
    # kind, duration_ms, three dominant spectral targets. 16 kHz source rate
    # preserves consonant energy up to 7.2 kHz before deterministic 48 kHz
    # conversion for HDA.
    "a":  ("v", 110, (730, 1090, 2440)),
    "e":  ("v", 105, (530, 1840, 2480)),
    "i":  ("v", 100, (270, 2290, 3010)),
    "o":  ("v", 110, (570, 840, 2410)),
    "u":  ("v", 100, (300, 870, 2240)),
    "eu": ("v", 110, (420, 1550, 2480)),
    "on": ("n", 115, (500, 1000, 2200)),
    "n":  ("n", 72,  (260, 1000, 2500)),
    "m":  ("n", 76,  (250, 900, 2350)),
    "r":  ("r", 70,  (500, 1500, 3200)),
    "l":  ("l", 72,  (390, 1500, 3000)),
    "w":  ("v", 65,  (330, 900, 2500)),
    "s":  ("f", 82,  (3000, 5200, 7000)),
    "sh": ("f", 88,  (1800, 3300, 5200)),
    "f":  ("f", 82,  (1200, 3000, 6000)),
    "v":  ("z", 82,  (900, 2400, 4800)),
    "z":  ("z", 82,  (1400, 3600, 6200)),
    "zh": ("z", 88,  (1200, 3000, 5200)),
    "t":  ("p", 65,  (2600, 5000, 7000)),
    "d":  ("p", 68,  (900, 2400, 4200)),
    "k":  ("p", 70,  (1800, 3600, 6200)),
    "g":  ("p", 72,  (800, 2200, 4000)),
    "p":  ("p", 65,  (1000, 3000, 6000)),
    "b":  ("p", 68,  (700, 1900, 3600)),
    "sil":("s", 70,  (0, 0, 0)),
}

WORDS = {
    "un": ("eu","n"),
    "continuer": ("k","on","t","i","n","u","e"),
    "deux": ("d","eu"),
    "aide": ("e","d"),
    "trois": ("t","r","w","a"),
    "recuperation": ("r","e","k","u","p","e","r","a","s","i","on"),
    "erreur": ("e","r","eu","r"),
    "non": ("n","on"),
}

def phrase(*words: str) -> tuple[str, ...]:
    out: list[str] = []
    for wi, word in enumerate(words):
        if wi:
            out.append("sil")
        out.extend(WORDS[word])
    return tuple(out)

PHRASES = {
    "startup": phrase("un","continuer","deux","aide","trois","recuperation"),
    "focus_accessibility": phrase("aide"),
    "focus_recovery": phrase("recuperation"),
    "help": phrase("aide"),
    "recovery": phrase("recuperation","non"),
    "invalid": phrase("erreur"),
    "continue": phrase("continuer"),
}

MARKERS = {
    "boot": b"QEVARYNOX-UEFI-NATIVE-SPEECH-V1\r\nEVENT=BOOT\r\nSYNTH=ALLOPHONE_CONCATENATIVE_V1\r\nFOCUS=CONTINUE\r\nSPEECH=DONE\r\nEND\r\n",
    "focus_accessibility": b"QEVARYNOX-UEFI-NATIVE-SPEECH-V1\r\nEVENT=FOCUS\r\nFOCUS=ACCESSIBILITY\r\nSPEECH=DONE\r\nEND\r\n",
    "focus_recovery": b"QEVARYNOX-UEFI-NATIVE-SPEECH-V1\r\nEVENT=FOCUS\r\nFOCUS=RECOVERY\r\nSPEECH=DONE\r\nEND\r\n",
    "focus_continue": b"QEVARYNOX-UEFI-NATIVE-SPEECH-V1\r\nEVENT=FOCUS\r\nFOCUS=CONTINUE\r\nSPEECH=DONE\r\nEND\r\n",
    "help": b"QEVARYNOX-UEFI-NATIVE-SPEECH-V1\r\nEVENT=ACTIVATE\r\nID=ACCESSIBILITY\r\nSTATUS=READY\r\nSPEECH=DONE\r\nEND\r\n",
    "recovery": b"QEVARYNOX-UEFI-NATIVE-SPEECH-V1\r\nEVENT=ACTIVATE\r\nID=RECOVERY\r\nSTATUS=BLOCKED\r\nSPEECH=DONE\r\nEND\r\n",
    "invalid": b"QEVARYNOX-UEFI-NATIVE-SPEECH-V1\r\nEVENT=INVALID_KEY\r\nSTATUS=BLOCKED\r\nSPEECH=DONE\r\nEND\r\n",
    "continue": b"QEVARYNOX-UEFI-NATIVE-SPEECH-V1\r\nEVENT=ACTIVATE\r\nID=CONTINUE\r\nSTATUS=CONFIRMED\r\nSPEECH=DONE\r\nEND\r\n",
    "fail": b"QEVARYNOX-UEFI-NATIVE-SPEECH-V1\r\nSTATUS=BLOCKED\r\nREASON=AUDIO_PATH_FAILED\r\nEND\r\n",
}

def _noise(seed: int) -> tuple[int, float]:
    seed ^= (seed << 13) & 0xFFFFFFFF
    seed ^= seed >> 17
    seed ^= (seed << 5) & 0xFFFFFFFF
    seed &= 0xFFFFFFFF
    return seed, ((seed & 0xFFFF) / 32767.5) - 1.0

class _Resonator:
    __slots__ = ("r", "c", "y1", "y2")
    def __init__(self, freq: float, bandwidth: float) -> None:
        import math
        freq = max(80.0, min(freq, SAMPLE_RATE * 0.45))
        bandwidth = max(70.0, bandwidth)
        self.r = math.exp(-math.pi * bandwidth / SAMPLE_RATE)
        self.c = 2.0 * self.r * math.cos(TAU * freq / SAMPLE_RATE)
        self.y1 = 0.0
        self.y2 = 0.0

    def step(self, x: float) -> float:
        y = (1.0 - self.r) * x + self.c * self.y1 - (self.r * self.r) * self.y2
        self.y2, self.y1 = self.y1, y
        return y

def make_unit(name: str, spec: tuple[str, int, tuple[int, int, int]]) -> bytes:
    import math
    kind, duration_ms, formants = spec
    count = max(1, SAMPLE_RATE * duration_ms // 1000)
    if kind == "s":
        return bytes([128]) * count

    # Screen-reader profile: clear mid/high spectrum, moderate F0, low breath.
    pitch = 168.0 if name not in ("i", "e") else 176.0
    bandwidths = (95.0, 150.0, 240.0)
    resonators = [_Resonator(f, bw) for f, bw in zip(formants, bandwidths)]
    seed = 0x51455641 ^ sum((i + 1) * ord(ch) for i, ch in enumerate(name))
    phase = 0.0
    dc = 0.0
    prev = 0.0
    floats: list[float] = []
    attack = max(1, int(SAMPLE_RATE * (0.0008 if kind == "p" else 0.0015)))
    release = max(1, int(SAMPLE_RATE * 0.0018))

    for idx in range(count):
        t = idx / SAMPLE_RATE
        env = min(1.0, idx / attack, (count - 1 - idx) / release)
        env = max(0.0, env)

        seed, jitter = _noise(seed)
        f0 = pitch * (1.0 + 0.006 * math.sin(TAU * 4.6 * t) + 0.0015 * jitter)
        phase += f0 / SAMPLE_RATE
        phase -= math.floor(phase)
        saw = 2.0 * phase - 1.0
        glottal = (1.0 - saw * saw) * (1.0 if phase < 0.60 else -0.30)
        glottal += 0.12 * math.sin(TAU * phase)

        seed, noise = _noise(seed)
        if kind == "v":
            source = 0.92 * glottal + 0.025 * noise
        elif kind in ("n", "l"):
            source = 0.78 * glottal + 0.06 * noise
        elif kind == "r":
            source = 0.46 * glottal + 0.42 * noise
        elif kind == "z":
            source = 0.42 * glottal + 0.72 * noise
        elif kind == "f":
            source = 0.98 * noise
        else:  # plosive: short high-energy burst followed by voiced/noise tail.
            burst_samples = max(1, int(SAMPLE_RATE * 0.010))
            burst = math.exp(-idx / max(1.0, burst_samples * 0.38))
            source = 0.92 * noise * burst + 0.14 * noise + 0.22 * glottal

        filtered = (
            0.95 * resonators[0].step(source) +
            0.58 * resonators[1].step(source) +
            0.32 * resonators[2].step(source)
        )
        x = (0.78 * filtered + 0.18 * source) * env

        # DC rejection + light pre-emphasis keeps consonants distinct after the
        # 8-bit unit bank is expanded to 48 kHz signed stereo.
        dc = 0.997 * dc + 0.003 * x
        hp = x - dc
        y = hp + 0.10 * (hp - prev)
        prev = hp
        floats.append(math.tanh(y * 1.35))

    mean = sum(floats) / max(1, len(floats))
    centered = [x - mean for x in floats]
    peak = max(1e-9, max(abs(x) for x in centered))
    scale = 0.88 / peak
    out = bytearray()
    for x in centered:
        val = int(round(128.0 + max(-1.0, min(1.0, x * scale)) * 112.0))
        out.append(max(0, min(255, val)))
    return bytes(out)

def make_units() -> dict[str, bytes]:
    # Hard fail instead of silently generating aliased speech. 0.45*Fs keeps
    # a small transition margin below Nyquist for the zero-order 48 kHz
    # conversion used by the HDA backends.
    spectral_limit = int(SAMPLE_RATE * 0.45)
    for name, (_, _, formants) in UNIT_SPECS.items():
        if any(freq < 0 or freq > spectral_limit for freq in formants):
            raise ValueError(
                f"{name}: formant target exceeds spectral budget "
                f"({formants!r}, limit={spectral_limit} Hz)"
            )
    return {name: make_unit(name, spec) for name, spec in UNIT_SPECS.items()}

class Code:
    def __init__(self) -> None:
        self.data = bytearray()
        self.labels: dict[str, int] = {}
        self.fixups: list[tuple[int, int, str, int]] = []

    def pos(self) -> int:
        return len(self.data)

    def emit(self, data: bytes) -> None:
        self.data += bytes(data)

    def label(self, name: str) -> None:
        self.labels[name] = self.pos()

    def rel32(self, opcode: bytes, label: str) -> None:
        self.emit(opcode)
        off = self.pos()
        self.emit(b"\0" * 4)
        self.fixups.append((off, self.pos(), label, 4))

    def rel8(self, opcode: int, label: str) -> None:
        self.emit(bytes((opcode, 0)))
        self.fixups.append((self.pos() - 1, self.pos(), label, 1))

    def lea_rsi_data(self, off: int) -> None:
        self.emit(b"\x48\x8d\x35")
        after = TEXT_RVA + self.pos() + 4
        self.emit(struct.pack("<i", DATA_RVA + off - after))

    def lea_r9_data(self, off: int) -> None:
        self.emit(b"\x4c\x8d\x0d")
        after = TEXT_RVA + self.pos() + 4
        self.emit(struct.pack("<i", DATA_RVA + off - after))

    def lea_rdx_data(self, off: int) -> None:
        self.emit(b"\x48\x8d\x15")
        after = TEXT_RVA + self.pos() + 4
        self.emit(struct.pack("<i", DATA_RVA + off - after))

    def mov_rax_data(self, off: int) -> None:
        self.emit(b"\x48\x8b\x05")
        after = TEXT_RVA + self.pos() + 4
        self.emit(struct.pack("<i", DATA_RVA + off - after))

    def mov_eax_data(self, off: int) -> None:
        self.emit(b"\x8b\x05")
        after = TEXT_RVA + self.pos() + 4
        self.emit(struct.pack("<i", DATA_RVA + off - after))

    def mov_data_eax(self, off: int) -> None:
        self.emit(b"\x89\x05")
        after = TEXT_RVA + self.pos() + 4
        self.emit(struct.pack("<i", DATA_RVA + off - after))

    def movzx_eax_data16(self, off: int) -> None:
        self.emit(b"\x0f\xb7\x05")
        after = TEXT_RVA + self.pos() + 4
        self.emit(struct.pack("<i", DATA_RVA + off - after))

    def patch(self) -> None:
        for off, after, label, width in self.fixups:
            disp = self.labels[label] - after
            if width == 4:
                struct.pack_into("<i", self.data, off, disp)
            else:
                if not -128 <= disp <= 127:
                    raise SystemExit(f"short branch overflow {label}: {disp}")
                self.data[off] = disp & 0xFF


def layout_data(units: dict[str, bytes]) -> tuple[bytes, dict[str, int]]:
    data = bytearray(0x100)
    offsets: dict[str, int] = {"maxaddr": 0, "keybuf": 8, "focus": 12}
    struct.pack_into("<Q", data, offsets["maxaddr"], 0x00FFFFFF)
    struct.pack_into("<I", data, offsets["focus"], 0)

    for name in sorted(units):
        offsets["unit_" + name] = len(data)
        data += units[name]

    for name, marker in MARKERS.items():
        offsets["marker_" + name] = len(data)
        data += marker

    return bytes(data), offsets


def build_code(units: dict[str, bytes], off: dict[str, int]) -> bytes:
    c = Code()

    c.emit(b"\x53\x56\x57")
    c.emit(b"\x41\x54\x41\x55\x41\x56\x41\x57")
    c.emit(b"\x48\x83\xec\x20")

    c.emit(b"\x49\x89\xd5")
    c.emit(b"\x4c\x8b\x72\x30")
    c.emit(b"\x4c\x8b\x7a\x60")

    for port, value in (
        (0x3F9, 0x00), (0x3FB, 0x80), (0x3F8, 0x03),
        (0x3F9, 0x00), (0x3FB, 0x03), (0x3FA, 0xC7), (0x3FC, 0x0B),
    ):
        c.emit(b"\x66\xba" + struct.pack("<H", port) + b"\xb0" + bytes((value,)) + b"\xee")

    c.emit(b"\xb9\x01\x00\x00\x00")
    c.emit(b"\xba\x04\x00\x00\x00")
    c.emit(b"\x41\xb8\x20\x00\x00\x00")
    c.lea_r9_data(off["maxaddr"])
    c.emit(b"\x49\x8b\x47\x28\xff\xd0")
    c.emit(b"\x48\x85\xc0")
    c.rel32(b"\x0f\x85", "fail")

    c.mov_rax_data(off["maxaddr"])
    c.emit(b"\x48\x05\xff\xff\x00\x00")
    c.emit(b"\x48\x25\x00\x00\xff\xff")
    c.emit(b"\x48\x89\xc3")
    c.emit(b"\x48\x81\xfb\x00\x00\x00\x01")
    c.rel32(b"\x0f\x83", "fail")

    c.emit(b"\x66\xba\x26\x02\xb0\x01\xee")
    c.emit(b"\xb9\x05\x00\x00\x00")
    c.emit(b"\x49\x8b\x87\xf8\x00\x00\x00\xff\xd0")
    c.emit(b"\x66\xba\x26\x02\x31\xc0\xee")
    c.emit(b"\xb9\x00\x00\x02\x00")
    c.label("reset_wait")
    c.emit(b"\x66\xba\x2e\x02\xec\xa8\x80")
    c.rel8(0x75, "reset_ready")
    c.emit(b"\xff\xc9")
    c.rel32(b"\x0f\x85", "reset_wait")
    c.rel32(b"\xe9", "fail")
    c.label("reset_ready")
    c.emit(b"\x66\xba\x2a\x02\xec\x3c\xaa")
    c.rel32(b"\x0f\x85", "fail")

    for value in (0xD1, 0x41, 0x1F, 0x40):
        c.emit(b"\x41\xb2" + bytes((value,)))
        c.rel32(b"\xe8", "dsp_write")

    def serial(name: str) -> None:
        marker = MARKERS[name]
        c.lea_rsi_data(off["marker_" + name])
        c.emit(b"\xb9" + struct.pack("<I", len(marker)))
        c.rel32(b"\xe8", "serial_emit")

    def speak(name: str) -> None:
        # Runtime concatenation: the EFI executes one playback operation per
        # first-party allophone unit. No full-utterance PCM is materialized.
        for unit_name in PHRASES[name]:
            c.lea_rsi_data(off["unit_" + unit_name])
            c.emit(b"\xb9" + struct.pack("<I", len(units[unit_name])))
            c.rel32(b"\xe8", "play_pcm")

    speak("startup")
    serial("boot")
    c.rel32(b"\xe9", "read")

    c.label("read")
    c.emit(b"\x4c\x89\xf1")
    c.lea_rdx_data(off["keybuf"])
    c.emit(b"\x49\x8b\x46\x08\xff\xd0")
    c.emit(b"\x48\x85\xc0")
    c.rel32(b"\x0f\x85", "read")

    c.movzx_eax_data16(off["keybuf"] + 2)
    c.emit(b"\x66\x3d\x0d\x00")
    c.rel32(b"\x0f\x84", "activate")

    c.emit(b"\x66\x3d\x31\x00")
    c.rel32(b"\x0f\x84", "direct_continue")
    c.emit(b"\x66\x3d\x32\x00")
    c.rel32(b"\x0f\x84", "direct_help")
    c.emit(b"\x66\x3d\x33\x00")
    c.rel32(b"\x0f\x84", "direct_recovery")

    c.movzx_eax_data16(off["keybuf"])
    c.emit(b"\x66\x3d\x01\x00")
    c.rel32(b"\x0f\x84", "up")
    c.emit(b"\x66\x3d\x02\x00")
    c.rel32(b"\x0f\x84", "down")
    c.rel32(b"\xe9", "invalid")

    c.label("down")
    c.mov_eax_data(off["focus"])
    c.emit(b"\xff\xc0")
    c.emit(b"\x83\xf8\x03")
    c.rel32(b"\x0f\x82", "store_focus")
    c.emit(b"\x31\xc0")
    c.rel32(b"\xe9", "store_focus")

    c.label("up")
    c.mov_eax_data(off["focus"])
    c.emit(b"\x85\xc0")
    c.rel32(b"\x0f\x85", "up_decrement")
    c.emit(b"\xb8\x02\x00\x00\x00")
    c.rel32(b"\xe9", "store_focus")
    c.label("up_decrement")
    c.emit(b"\xff\xc8")

    c.label("store_focus")
    c.mov_data_eax(off["focus"])
    c.emit(b"\x83\xf8\x00")
    c.rel32(b"\x0f\x84", "focus_continue")
    c.emit(b"\x83\xf8\x01")
    c.rel32(b"\x0f\x84", "focus_accessibility")
    c.rel32(b"\xe9", "focus_recovery")

    c.label("focus_continue")
    speak("startup")
    serial("focus_continue")
    c.rel32(b"\xe9", "read")

    c.label("focus_accessibility")
    speak("focus_accessibility")
    serial("focus_accessibility")
    c.rel32(b"\xe9", "read")

    c.label("focus_recovery")
    speak("focus_recovery")
    serial("focus_recovery")
    c.rel32(b"\xe9", "read")

    c.label("activate")
    c.mov_eax_data(off["focus"])
    c.emit(b"\x83\xf8\x00")
    c.rel32(b"\x0f\x84", "direct_continue")
    c.emit(b"\x83\xf8\x01")
    c.rel32(b"\x0f\x84", "direct_help")
    c.rel32(b"\xe9", "direct_recovery")

    c.label("direct_help")
    speak("help")
    serial("help")
    c.rel32(b"\xe9", "read")

    c.label("direct_recovery")
    speak("recovery")
    serial("recovery")
    c.rel32(b"\xe9", "read")

    c.label("invalid")
    speak("invalid")
    serial("invalid")
    c.rel32(b"\xe9", "read")

    c.label("direct_continue")
    speak("continue")
    serial("continue")
    c.emit(b"\x31\xc0")
    c.rel32(b"\xe9", "epilogue")

    c.label("fail")
    serial("fail")
    c.emit(b"\xb8\x01\x00\x00\x00")

    c.label("epilogue")
    c.emit(b"\x48\x83\xc4\x20")
    c.emit(b"\x41\x5f\x41\x5e\x41\x5d\x41\x5c")
    c.emit(b"\x5f\x5e\x5b\xc3")

    c.label("play_pcm")
    c.emit(b"\x41\x89\xcc")
    c.emit(b"\x48\x89\xdf")
    c.emit(b"\xf3\xa4")

    for port, value in ((0x0A, 0x05), (0x0C, 0x00), (0x0B, 0x49)):
        c.emit(b"\x66\xba" + struct.pack("<H", port) + b"\xb0" + bytes((value,)) + b"\xee")
    c.emit(b"\x48\x89\xd8\x48\xc1\xe8\x10\x66\xba\x83\x00\xee")
    c.emit(b"\x48\x89\xd8\x66\xba\x02\x00\xee\x48\xc1\xe8\x08\xee")
    c.emit(b"\x44\x89\xe0\xff\xc8")
    c.emit(b"\x66\xba\x03\x00\xee\xc1\xe8\x08\xee")
    c.emit(b"\x66\xba\x0a\x00\xb0\x01\xee")

    for value in (0xC0, 0x00):
        c.emit(b"\x41\xb2" + bytes((value,)))
        c.rel32(b"\xe8", "dsp_write")
    c.emit(b"\x44\x89\xe0\xff\xc8")
    c.emit(b"\x41\x88\xc2")
    c.rel32(b"\xe8", "dsp_write")
    c.emit(b"\x44\x89\xe0\xff\xc8\xc1\xe8\x08")
    c.emit(b"\x41\x88\xc2")
    c.rel32(b"\xe8", "dsp_write")

    c.emit(b"\x41\x6b\xcc\x7d")
    c.emit(b"\x81\xc1\xa8\x61\x00\x00")
    c.emit(b"\x49\x8b\x87\xf8\x00\x00\x00\xff\xd0")
    c.emit(b"\xc3")

    c.label("dsp_write")
    c.emit(b"\x66\xba\x2c\x02")
    c.label("dsp_wait")
    c.emit(b"\xec\xa8\x80")
    c.rel8(0x75, "dsp_wait")
    c.emit(b"\x44\x88\xd0\xee\xc3")

    c.label("serial_emit")
    c.emit(b"\x66\xba\xfd\x03")
    c.label("serial_wait")
    c.emit(b"\xec\xa8\x20")
    c.rel8(0x74, "serial_wait")
    c.emit(b"\x66\xba\xf8\x03\x8a\x06\xee\x48\xff\xc6\x66\xba\xfd\x03\xff\xc9")
    c.rel8(0x75, "serial_wait")
    c.emit(b"\xc3")

    c.patch()
    return bytes(c.data)


def put(buf: bytearray, off: int, fmt: str, *values: int) -> None:
    struct.pack_into(fmt, buf, off, *values)


def build(units: dict[str, bytes]) -> bytes:
    payload, offsets = layout_data(units)
    code = build_code(units, offsets)
    if len(code) > 0x3000:
        raise SystemExit(f"text too large: {len(code)}")
    if len(payload) > 0x30000:
        raise SystemExit(f"data too large: {len(payload)}")

    text_raw = 0x200
    text_raw_size = (len(code) + 0x1FF) & ~0x1FF
    data_raw = text_raw + text_raw_size
    data_raw_size = (len(payload) + 0x1FF) & ~0x1FF
    reloc_rva = (DATA_RVA + len(payload) + 0xFFF) & ~0xFFF
    reloc_raw = data_raw + data_raw_size
    file_size = reloc_raw + 0x200
    image_size = reloc_rva + 0x1000

    image = bytearray(file_size)
    put(image, 0x00, "<H", 0x5A4D)
    put(image, 0x3C, "<I", 0x80)
    pe = 0x80
    image[pe:pe+4] = b"PE\0\0"
    coff = pe + 4
    put(image, coff, "<HHIIIHH", 0x8664, 3, 0, 0, 0, 0xF0, 0x0022)

    opt = coff + 20
    put(image, opt + 0x00, "<H", 0x20B)
    put(image, opt + 0x04, "<I", text_raw_size)
    put(image, opt + 0x08, "<I", data_raw_size + 0x200)
    put(image, opt + 0x10, "<I", TEXT_RVA)
    put(image, opt + 0x14, "<I", TEXT_RVA)
    put(image, opt + 0x18, "<Q", 0x400000)
    put(image, opt + 0x20, "<I", 0x1000)
    put(image, opt + 0x24, "<I", 0x200)
    put(image, opt + 0x38, "<I", image_size)
    put(image, opt + 0x3C, "<I", 0x200)
    put(image, opt + 0x44, "<H", 10)
    put(image, opt + 0x48, "<Q", 0x100000)
    put(image, opt + 0x50, "<Q", 0x1000)
    put(image, opt + 0x58, "<Q", 0x100000)
    put(image, opt + 0x60, "<Q", 0x1000)
    put(image, opt + 0x6C, "<I", 16)
    put(image, opt + 0x70 + 5 * 8, "<II", reloc_rva, 8)

    sec = opt + 0xF0
    image[sec:sec+8] = b".text\0\0\0"
    put(image, sec + 0x08, "<I", len(code))
    put(image, sec + 0x0C, "<I", TEXT_RVA)
    put(image, sec + 0x10, "<I", text_raw_size)
    put(image, sec + 0x14, "<I", text_raw)
    put(image, sec + 0x24, "<I", 0x60000020)

    data = sec + 40
    image[data:data+8] = b".data\0\0\0"
    put(image, data + 0x08, "<I", len(payload))
    put(image, data + 0x0C, "<I", DATA_RVA)
    put(image, data + 0x10, "<I", data_raw_size)
    put(image, data + 0x14, "<I", data_raw)
    put(image, data + 0x24, "<I", 0xC0000040)

    reloc = sec + 80
    image[reloc:reloc+8] = b".reloc\0\0"
    put(image, reloc + 0x08, "<I", 8)
    put(image, reloc + 0x0C, "<I", reloc_rva)
    put(image, reloc + 0x10, "<I", 0x200)
    put(image, reloc + 0x14, "<I", reloc_raw)
    put(image, reloc + 0x24, "<I", 0x42000040)

    image[text_raw:text_raw+len(code)] = code
    image[data_raw:data_raw+len(payload)] = payload
    put(image, reloc_raw, "<II", TEXT_RVA, 8)
    return bytes(image)


def validate(image: bytes, units: dict[str, bytes]) -> None:
    if image[:2] != b"MZ":
        raise SystemExit("missing MZ")
    pe = struct.unpack_from("<I", image, 0x3C)[0]
    if image[pe:pe+4] != b"PE\0\0":
        raise SystemExit("missing PE")
    coff = pe + 4
    machine, sections = struct.unpack_from("<HH", image, coff)
    if (machine, sections) != (0x8664, 3):
        raise SystemExit("unexpected machine/section count")
    opt = coff + 20
    if struct.unpack_from("<H", image, opt)[0] != 0x20B:
        raise SystemExit("not PE32+")
    if struct.unpack_from("<H", image, opt + 0x44)[0] != 10:
        raise SystemExit("not EFI application")
    sec = opt + 0xF0
    data = sec + 40
    text_chars = struct.unpack_from("<I", image, sec + 0x24)[0]
    data_chars = struct.unpack_from("<I", image, data + 0x24)[0]
    if text_chars & 0x80000000:
        raise SystemExit("W+X text")
    if not (data_chars & 0x80000000) or (data_chars & 0x20000000):
        raise SystemExit("data permissions invalid")
    for name, pcm in units.items():
        if pcm not in image:
            raise SystemExit(f"speech unit not bound: {name}")
    if b"SYNTH=ALLOPHONE_CONCATENATIVE_V1" not in image:
        raise SystemExit("native speech marker missing")


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: build_uefi_native_speech.py OUTPUT")
    units = make_units()
    image = build(units)
    validate(image, units)
    out = Path(sys.argv[1])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(image)
    print("OS_UEFI_NATIVE_SPEECH_BUILD=PASS")
    print("image-sha256=" + hashlib.sha256(image).hexdigest())
    print("bytes=" + str(len(image)))
    print("sample-rate=" + str(SAMPLE_RATE))
    print("speech-units=" + str(len(units)))
    print("largest-unit-bytes=" + str(max(map(len, units.values()))))
    print("full-utterance-pcm-assets=0")
    print("external-tts-dependency=0")


if __name__ == "__main__":
    main()
